"""
Use stopwords generated by nltk
"""

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
STOPWORDS = stopwords.words('english')
STOPWORDS = set(STOPWORDS)

def symbol_scrub(wordlist):
    return [x for x in wordlist if len(x) != 1 or x.isalnum()]

def scrub(wordlist):
    results = []
    for word in wordlist:
        lower_word = word.lower()
        if len(lower_word) < 2:
            continue
        elif lower_word in STOPWORDS:
            continue
        elif lower_word[:2] == "\\u":
            continue
        elif word.isnumeric():
            continue
        results.append(word)
    return results
